Alter samples of preferred name for reference and dataset author lists
elifesciences/api-raml pull request #265
Opened 2021-03-08 13:17 UTC by nlisgo

2021-03-09 01:52 UTC, lsh-0 commented on CHANGELOG.md
> +* altered the sample values for author preferred names in references and datasets
Not a good description. Perhaps:

> author `preferred` field changed from "surname firstname" to "firstname surname" in references and datasets

2021-03-09 01:56 UTC, lsh-0 commented on CHANGELOG.md
> +## 2.0.1
Patch versions are for backwards compatible bugfixes typically (https://semver.org).

In this case we're probably going for `2.1.0`. It's still a significant change but it doesn't break our public API.

2021-03-09 02:01 UTC, lsh-0 commented on CHANGELOG.md
> +* altered the sample values for author preferred names in references and datasets
looking at the article changes I guess the "One Person" and "Person One" examples aren't that clear. If this is what is happening:

>\-                         "preferred": "C Darwin",
>\+                       "preferred": "Darwin C",

Then the description would be:

> author preferred field changed from "firstname surname" to "surname firstname" in references and datasets

Anyway, your decision.

2021-03-09 02:05 UTC, lsh-0 requested changes
that is a helluva lot of changes to have made, I hope you wrote a script :| 

I didn't see any other change except to examples, so I guess the actual logic lives in the xml/bot-lax.

apart from the description and version number in the changelog it should be good to go.

2021-03-09 02:10 UTC, lsh-0 commented on CHANGELOG.md
> +## 2.0.1
I think arguments could be made for this being a major or minor *or* patch version the more I think about it. Minor version still seems more sensible to me, preserving the patch version for more innocuous changes later.

2021-03-09 14:28 UTC, nlisgo commented
> that is a helluva lot of changes to have made, I hope you wrote a script :|

Regex!

> I didn't see any other change except to examples, so I guess the actual logic lives in the xml/bot-lax.

Yes.

> apart from the description and version number in the changelog it should be good to go.

Changed to minor version bump and amended the description. Found some more examples in the samples that I've added to the PR. Approve if you're happy and I'll merge it in on Thursday.

2021-03-10 23:43 UTC, lsh-0 approved these changes

2021-03-16 13:25 UTC, merged